name: Website Deployment
on:
  push:
    branches:
      - main
    paths:
      - 'website/**'

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache/restore dependencies
        uses: actions/cache@v3
        with:
          path: ./website/.yarn
          key: website-${{ hashFiles('website/yarn.lock') }}
      - name: Install dependencies
        run: yarn
        working-directory: ./website
      - name: Deploy
        run: |
          git config --global user.name ${{ secrets.GH_BOT_NAME }}
          git config --global user.email ${{ secrets.GH_BOT_EMAIL }}
          echo "machine github.com login ${{ secrets.GH_BOT_NAME }} password ${{ secrets.GH_RELEASE_TOKEN }}" > ~/.netrc
          GIT_USER=${{ secrets.GH_BOT_NAME }} yarn run deploy
        working-directory: ./website
